# Generated by Django 5.0.2 on 2025-02-01 17:18

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_bn',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer (Bengali)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=ckeditor.fields.RichTextField(verbose_name='Answer (English)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_hi',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer (Hindi)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Question (Bengali)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(verbose_name='Question (English)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Question (Hindi)'),
        ),
    ]
