# Generated by Django 5.0.2 on 2025-02-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_options_alter_faq_answer_bn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
    ]
